#!/usr/bin/env bash
# Fixture tests for scripts/ci/bump_version.sh (spec 048 FR-005/006/007/009/014).

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
helper="${repo_root}/scripts/ci/bump_version.sh"

if [[ ! -f "${helper}" ]]; then
  echo "Missing bump helper: ${helper}" >&2
  exit 1
fi

fixture_root="$(mktemp -d "${TMPDIR:-/tmp}/traverse-bump-version.XXXXXX")"
cleanup() {
  rm -rf "${fixture_root}"
}
trap cleanup EXIT
# Avoid copying host git template hooks into the fixture.
export GIT_TEMPLATE_DIR="${fixture_root}/empty-template"
mkdir -p "${GIT_TEMPLATE_DIR}"

seed_fixture() {
  local root="$1"
  local cargo_version="$2"
  local web_version="$3"

  mkdir -p "${root}/packages/web/TraverseEmbedder" "${root}/scripts/ci"
  cp "${helper}" "${root}/scripts/ci/bump_version.sh"

  cat > "${root}/Cargo.toml" <<EOF
[workspace]
members = []
resolver = "2"

[workspace.package]
version = "${cargo_version}"
edition = "2021"

[workspace.dependencies]
traverse-contracts = { path = "crates/traverse-contracts", version = "${cargo_version}" }
EOF

  cat > "${root}/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "traverse-contracts"
version = "${cargo_version}"
EOF

  cat > "${root}/packages/web/TraverseEmbedder/package.json" <<EOF
{
  "name": "traverse-embedder-web",
  "version": "${web_version}"
}
EOF

  cat > "${root}/packages/web/TraverseEmbedder/package-lock.json" <<EOF
{
  "name": "traverse-embedder-web",
  "version": "${web_version}",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": {
      "name": "traverse-embedder-web",
      "version": "${web_version}"
    }
  }
}
EOF

  git -C "${root}" init -q
  git -C "${root}" config user.email "bump-version-test@traverse.local"
  git -C "${root}" config user.name "Bump Version Test"
  git -C "${root}" add .
  git -C "${root}" commit -qm "seed fixture at cargo ${cargo_version} web ${web_version}"
}

run_helper() {
  local root="$1"
  shift
  # bump_version.sh resolves the repo via cwd + git rev-parse; run inside the fixture.
  (cd "${root}" && bash scripts/ci/bump_version.sh "$@")
}

assert_contains() {
  local haystack="$1"
  local needle="$2"
  local label="$3"
  if [[ "${haystack}" != *"${needle}"* ]]; then
    echo "FAIL: ${label} — expected output to contain: ${needle}" >&2
    echo "${haystack}" >&2
    exit 1
  fi
}

# --- invalid semver ---
invalid_root="${fixture_root}/invalid"
seed_fixture "${invalid_root}" "0.10.2" "0.10.2"
set +e
invalid_out="$(run_helper "${invalid_root}" foo 2>&1)"
invalid_status=$?
set -e
if [[ "${invalid_status}" -eq 0 ]]; then
  echo "FAIL: invalid semver should exit non-zero" >&2
  exit 1
fi
assert_contains "${invalid_out}" "Invalid semver" "invalid semver"

# --- dirty tree ---
dirty_root="${fixture_root}/dirty"
seed_fixture "${dirty_root}" "0.10.2" "0.10.2"
echo dirty > "${dirty_root}/extra.txt"
set +e
dirty_out="$(run_helper "${dirty_root}" 0.10.3 2>&1)"
dirty_status=$?
set -e
if [[ "${dirty_status}" -eq 0 ]]; then
  echo "FAIL: dirty tree should exit non-zero" >&2
  exit 1
fi
assert_contains "${dirty_out}" "Working tree is dirty" "dirty tree"

# --- mismatched pre-existing web version, happy path ---
mismatch_root="${fixture_root}/mismatch"
seed_fixture "${mismatch_root}" "0.10.2" "0.9.0"
run_helper "${mismatch_root}" 0.11.0 >/dev/null

cargo_version="$(awk '
  /^\[workspace\.package\]$/ { in_workspace_package = 1; next }
  /^\[/ { in_workspace_package = 0 }
  in_workspace_package && $1 == "version" {
    gsub(/"/, "", $3)
    print $3
    exit
  }
' "${mismatch_root}/Cargo.toml")"
web_version="$(node -p "require('${mismatch_root}/packages/web/TraverseEmbedder/package.json').version")"
lock_version="$(node -p "require('${mismatch_root}/packages/web/TraverseEmbedder/package-lock.json').version")"
packages_version="$(node -p "require('${mismatch_root}/packages/web/TraverseEmbedder/package-lock.json').packages[''].version")"

if [[ "${cargo_version}" != "0.11.0" ]]; then
  echo "FAIL: Cargo.toml version is ${cargo_version}, expected 0.11.0" >&2
  exit 1
fi
if [[ "${web_version}" != "0.11.0" || "${lock_version}" != "0.11.0" || "${packages_version}" != "0.11.0" ]]; then
  echo "FAIL: web versions not lockstep (package=${web_version} lock=${lock_version} packages=${packages_version})" >&2
  exit 1
fi
if ! git -C "${mismatch_root}" rev-parse --verify --quiet refs/tags/v0.11.0 >/dev/null; then
  echo "FAIL: missing local tag v0.11.0" >&2
  exit 1
fi
if ! git -C "${mismatch_root}" rev-parse --verify --quiet refs/tags/web-v0.11.0 >/dev/null; then
  echo "FAIL: missing local tag web-v0.11.0" >&2
  exit 1
fi

echo "bump_version.sh fixture tests passed."
