import test from "node:test";
import assert from "node:assert/strict";
import { createHash, createPrivateKey, sign } from "node:crypto";
import { readFileSync } from "node:fs";
import {
  ExactModelBrowserHost,
  ExactModelError,
  ModelIoStore,
  encodeGuestFrame,
  modelSigningKeyId,
  normalizeModelExecuteEvidence,
  PLACEMENT_WASM_CPU,
} from "../dist/index.js";

// Signed Spec 138 fixtures (Decision 101), regenerated by
// scripts/fixtures/sign-model-fixtures.mjs. The key is TEST-ONLY.
const MODELS = new URL("../../../../fixtures/models/", import.meta.url);
const readModelFile = (path) => new Uint8Array(readFileSync(new URL(path, MODELS)));
const TEST_KEY = JSON.parse(readFileSync(new URL("test-signing-key.json", MODELS), "utf8"));
const VECTOR = JSON.parse(readFileSync(new URL("conformance/signed-classifier.json", MODELS), "utf8"));
const TRUST = { trustedPublicKeysHex: [TEST_KEY.public_key_hex], modelUsage: "commercial" };

function fixture(dir) {
  return {
    manifest: readModelFile(`${dir}/model.manifest.json`),
    wasm: readModelFile(`${dir}/model.wasm`),
    sig: readModelFile(`${dir}/model.sig.json`),
  };
}

async function sha256Hex(bytes) {
  const hash = await crypto.subtle.digest("SHA-256", bytes);
  return [...new Uint8Array(hash)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

async function pinFor(modelId, manifestBytes, overrides = {}) {
  return {
    model_id: modelId,
    version: "1.0.0",
    digest: await sha256Hex(manifestBytes),
    offline_allowed: true,
    target: PLACEMENT_WASM_CPU,
    rights: { license_id: "Apache-2.0", commercial_use: "allowed" },
    ...overrides,
  };
}

function signWith(seedHex, manifestBytes) {
  const key = createPrivateKey({
    key: Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), Buffer.from(seedHex, "hex")]),
    format: "der",
    type: "pkcs8",
  });
  return sign(null, manifestBytes, key).toString("hex");
}

/** Re-sign an edited manifest with the test key (valid signature, bad content). */
function resigned(manifestBytes, edit) {
  const value = JSON.parse(new TextDecoder().decode(manifestBytes));
  edit(value);
  const bytes = new TextEncoder().encode(JSON.stringify(value));
  const sig = new TextEncoder().encode(
    JSON.stringify({ alg: "ed25519", key_id: TEST_KEY.key_id, signature: signWith(TEST_KEY.secret_key_hex, bytes) }),
  );
  return { bytes, sig };
}

async function registeredHost(dir, modelId, pinOverrides = {}) {
  const pkg = fixture(dir);
  const pin = await pinFor(modelId, pkg.manifest, pinOverrides);
  const host = new ExactModelBrowserHost([pin], TRUST);
  const digest = await host.registerPackage(pkg.manifest, pkg.wasm, pkg.sig);
  return { host, digest, pin };
}

function executeArgs(modelId, digest, input_ref, schema, extra = {}) {
  return {
    model_ref: { model_id: modelId, version: "1.0.0", digest },
    input_ref,
    policy_ref: "policy-1",
    data_classification: "sensitive",
    input_schema_ref: schema,
    input_schema_version: "1.0.0",
    max_output_bytes: 4096,
    allowed_classifications: ["sensitive"],
    ...extra,
  };
}

const reason = (expected, code = "model_incompatible") => (error) =>
  error instanceof ExactModelError && error.code === code && error.reason === expected;

test("signed echo fixture verifies, executes, and returns typed output + trace", async () => {
  const { host, digest } = await registeredHost("fixture-echo-1.0.0", "fixture.echo");
  assert.equal(await modelSigningKeyId(Buffer.from(TEST_KEY.public_key_hex, "hex")), TEST_KEY.key_id);
  // Distinctive payload: the trace carries public signed rights text, so the
  // redaction check must look for tensor bytes no rights field contains.
  const frame = encodeGuestFrame(1, [4], new TextEncoder().encode("q7zx"));
  const input_ref = host.io.stageModelInput(frame, 4096);
  const result = await host.execute(executeArgs("fixture.echo", digest, input_ref, "schema:fixture-in"));
  assert.equal(result.placement, PLACEMENT_WASM_CPU);
  assert.equal(result.target, PLACEMENT_WASM_CPU);
  assert.deepEqual(result.model_ref, { model_id: "fixture.echo", version: "1.0.0", digest });
  assert.equal(result.trace.digest, digest);
  assert.equal(result.trace.data_classification, "sensitive");
  assert.equal(result.trace.usage.input_bytes, frame.length);
  assert.equal(result.trace.usage.output_bytes, frame.length);
  assert.ok(!JSON.stringify(result.trace).includes("q7zx"), "trace must redact tensor bytes");
  assert.deepEqual(result.trace.model_evidence, result.model_evidence);
  assert.equal(result.model_evidence.status, "active");
  assert.equal(result.model_evidence.effective_usage, "commercial");
  const output = host.io.readModelOutput(result.output_ref, 4096);
  assert.deepEqual([...output], [...frame]);

  const rights = host.modelRights(`sha256:${digest}`);
  assert.equal(rights.license_id, "Apache-2.0");
  assert.equal(rights.commercial_use, "allowed");
  assert.ok(rights.attribution && rights.redistribution && rights.source_url.startsWith("https://"));
  assert.equal(host.modelRights("missing"), undefined);

  const browserEvidence = normalizeModelExecuteEvidence({
    status: "ok",
    model_ref: result.model_ref,
    placement: result.placement,
    output_ref: result.output_ref,
  });
  const nativeEvidence = normalizeModelExecuteEvidence({
    status: "ok",
    model_ref: result.model_ref,
    placement: PLACEMENT_WASM_CPU,
    artifact_ref: "output-1",
  });
  assert.equal(browserEvidence.governing_spec, nativeEvidence.governing_spec);
  assert.equal(browserEvidence.status, nativeEvidence.status);
  assert.equal(browserEvidence.placement, nativeEvidence.placement);
  assert.equal(browserEvidence.has_output_ref, true);
});

test("signed classifier conformance vector matches native output byte-for-byte", async () => {
  const pkg = fixture(VECTOR.package_dir);
  const host = new ExactModelBrowserHost([VECTOR.pin], { trustedPublicKeysHex: [VECTOR.trusted_public_key_hex], modelUsage: "commercial" });
  const digest = await host.registerPackage(pkg.manifest, pkg.wasm, pkg.sig);
  assert.equal(digest, VECTOR.pin.digest);
  const input_ref = host.io.stageModelInput(Buffer.from(VECTOR.request.input_frame_hex, "hex"), 4096);
  const result = await host.execute(
    executeArgs(VECTOR.pin.model_id, digest, input_ref, VECTOR.request.input_schema_ref),
  );
  assert.equal(result.placement, VECTOR.expected.placement);
  const output = host.io.readModelOutput(result.output_ref, 4096);
  assert.equal(Buffer.from(output).toString("hex"), VECTOR.expected.output_frame_hex);
});

test("trained digits MLP (#1461) matches the native vector and clears the accuracy floor", async () => {
  const vector = JSON.parse(readFileSync(new URL("conformance/signed-digits-mlp.json", MODELS), "utf8"));
  const pkg = fixture(vector.package_dir);
  const host = new ExactModelBrowserHost([vector.pin], { trustedPublicKeysHex: [vector.trusted_public_key_hex], modelUsage: "commercial" });
  const digest = await host.registerPackage(pkg.manifest, pkg.wasm, pkg.sig);
  assert.equal(host.modelRights(digest).license_id, "CC-BY-4.0");
  const run = async (frame) => {
    const input_ref = host.io.stageModelInput(frame, 268);
    const result = await host.execute(
      executeArgs(vector.pin.model_id, digest, input_ref, vector.request.input_schema_ref, { max_output_bytes: 64 }),
    );
    return host.io.readModelOutput(result.output_ref, 64);
  };
  for (const testCase of vector.cases) {
    const output = await run(Buffer.from(testCase.input_frame_hex, "hex"));
    assert.equal(Buffer.from(output).toString("hex"), testCase.output_frame_hex);
  }
  // Full held-out split through the browser host: same count as native.
  const rows = readFileSync(new URL("../datasets/uci-optdigits/optdigits.tes", MODELS), "utf8").trim().split("\n");
  let correct = 0;
  for (const line of rows) {
    const values = line.split(",").map(Number);
    const label = values.pop();
    const output = await run(encodeGuestFrame(2, [64], new Uint8Array(Float32Array.from(values).buffer)));
    const view = new DataView(output.buffer, output.byteOffset, output.byteLength);
    correct += view.getFloat32(52, true) === label ? 1 : 0;
  }
  assert.equal(rows.length, 1797);
  assert.ok(correct / rows.length >= 0.95);
  assert.equal(correct, 1727);
});

test("classifier fixture computes real inference, not a pass-through", async () => {
  const { host, digest } = await registeredHost("fixture-classifier-1.0.0", "fixture.classifier");
  const features = Float32Array.from([1.0, 2.0, -1.0, 4.0]);
  const frame = encodeGuestFrame(2, [4], new Uint8Array(features.buffer));
  const input_ref = host.io.stageModelInput(frame, 4096);
  const result = await host.execute(
    executeArgs("fixture.classifier", digest, input_ref, "schema:fixture-classifier-in"),
  );
  const output = host.io.readModelOutput(result.output_ref, 4096);
  assert.notDeepEqual([...output], [...frame], "classifier output must not echo the input");
  const view = new DataView(output.buffer, output.byteOffset, output.byteLength);
  assert.equal(view.getUint16(0, true), 1);
  assert.equal(output[2], 3);
  assert.equal(view.getUint32(4, true), 2);
  // 0.5*1.0 - 0.25*2.0 + 1.0*-1.0 + 0.75*4.0 - 0.5 == 1.5
  assert.ok(Math.abs(view.getFloat32(12, true) - 1.5) < 1e-6);
  assert.ok(Math.abs(view.getFloat32(16, true) - 1.0) < 1e-6);
});

async function runResponderPrompt(promptText) {
  const { host, digest } = await registeredHost("fixture-responder-1.0.0", "fixture.responder");
  const promptBytes = new TextEncoder().encode(promptText);
  const frame = encodeGuestFrame(4, [promptBytes.length], promptBytes);
  const input_ref = host.io.stageModelInput(frame, 4096);
  const result = await host.execute(executeArgs("fixture.responder", digest, input_ref, "schema:bridged-generate-in"));
  const output = host.io.readModelOutput(result.output_ref, 4096);
  const view = new DataView(output.buffer, output.byteOffset, output.byteLength);
  return new TextDecoder().decode(output.slice(12, 12 + view.getUint32(8, true)));
}

test("bridge fixture (#1455) returns the keyword-matched and fallback responses", async () => {
  assert.equal(await runResponderPrompt("hi there, how are you?"), "hi there");
  assert.equal(await runResponderPrompt("what is the weather today"), "hmm");
});

test("register + execute make zero network calls once the package is cached", async () => {
  const originalFetch = globalThis.fetch;
  const OriginalXhr = globalThis.XMLHttpRequest;
  let calls = 0;
  globalThis.fetch = () => {
    calls += 1;
    throw new Error("network forbidden");
  };
  globalThis.XMLHttpRequest = function () {
    calls += 1;
    throw new Error("network forbidden");
  };
  try {
    const { host, digest } = await registeredHost("fixture-echo-1.0.0", "fixture.echo");
    const input_ref = host.io.stageModelInput(new Uint8Array([1, 2, 3]), 64);
    await host.execute(executeArgs("fixture.echo", digest, input_ref, "schema:fixture-in"));
  } finally {
    globalThis.fetch = originalFetch;
    globalThis.XMLHttpRequest = OriginalXhr;
  }
  assert.equal(calls, 0);
});

test("offline cache miss is model_unavailable; unknown model_ref is pin_mismatch", async () => {
  const pkg = fixture("fixture-echo-1.0.0");
  const pin = await pinFor("fixture.echo", pkg.manifest);
  const host = new ExactModelBrowserHost([pin], TRUST);
  const input_ref = host.io.stageModelInput(new Uint8Array([1, 2, 3]), 64);
  await assert.rejects(
    () => host.execute(executeArgs("fixture.echo", pin.digest, input_ref, "schema:fixture-in")),
    (error) => error.code === "model_unavailable" && error.reason === undefined,
  );
  await assert.rejects(
    () => host.execute(executeArgs("fixture.other", pin.digest, input_ref, "schema:fixture-in")),
    reason("pin_mismatch", "model_unavailable"),
  );
});

test("registration rejects unsigned, bad-signature, and untrusted-key packages", async () => {
  const pkg = fixture("fixture-echo-1.0.0");
  const pin = await pinFor("fixture.echo", pkg.manifest);
  const host = new ExactModelBrowserHost([pin], TRUST);
  const enc = (value) => new TextEncoder().encode(JSON.stringify(value));
  const sigDoc = JSON.parse(new TextDecoder().decode(pkg.sig));
  const bad = (sig) => host.registerPackage(pkg.manifest, pkg.wasm, sig);

  await assert.rejects(() => bad(new Uint8Array(0)), reason("signature_invalid"));
  await assert.rejects(() => bad(enc({ ...sigDoc, extra: 1 })), reason("signature_invalid"));
  await assert.rejects(() => bad(enc({ ...sigDoc, alg: "rsa" })), reason("signature_invalid"));
  await assert.rejects(() => bad(enc({ ...sigDoc, signature: "zz" })), reason("signature_invalid"));
  await assert.rejects(() => bad(enc({ ...sigDoc, signature: "00".repeat(64) })), reason("signature_invalid"));
  await assert.rejects(
    () => host.registerPackage(new TextEncoder().encode(" "), pkg.wasm, pkg.sig),
    reason("signature_invalid"),
  );
  await assert.rejects(() => bad(enc({ ...sigDoc, key_id: "ed25519:unknown" })), reason("key_untrusted"));
  const otherSeed = "07".repeat(32);
  const otherKeyId = await modelSigningKeyId(
    Buffer.from(createPrivateKey({
      key: Buffer.concat([Buffer.from("302e020100300506032b657004220420", "hex"), Buffer.from(otherSeed, "hex")]),
      format: "der",
      type: "pkcs8",
    }).export({ format: "jwk" }).x, "base64url"),
  );
  await assert.rejects(
    () => bad(enc({ alg: "ed25519", key_id: otherKeyId, signature: signWith(otherSeed, pkg.manifest) })),
    reason("key_untrusted"),
  );
  const noTrust = new ExactModelBrowserHost([pin], { trustedPublicKeysHex: [], modelUsage: "commercial" });
  await assert.rejects(() => noTrust.registerPackage(pkg.manifest, pkg.wasm, pkg.sig), reason("key_untrusted"));
  const badKey = new ExactModelBrowserHost([pin], { trustedPublicKeysHex: ["abcd"], modelUsage: "commercial" });
  await assert.rejects(() => badKey.registerPackage(pkg.manifest, pkg.wasm, pkg.sig), reason("key_untrusted"));

  const narrowedWrong = new ExactModelBrowserHost([{ ...pin, key_id: "ed25519:other" }], TRUST);
  await assert.rejects(() => narrowedWrong.registerPackage(pkg.manifest, pkg.wasm, pkg.sig), reason("key_untrusted"));
  const narrowed = new ExactModelBrowserHost([{ ...pin, key_id: TEST_KEY.key_id }], TRUST);
  assert.equal(await narrowed.registerPackage(pkg.manifest, pkg.wasm, pkg.sig), pin.digest);
});

test("registration rejects missing, ambiguous, digest, rights, and target mismatches", async () => {
  const pkg = fixture("fixture-echo-1.0.0");
  const pin = await pinFor("fixture.echo", pkg.manifest);
  const register = (pins, manifest = pkg.manifest, wasm = pkg.wasm, sig = pkg.sig) =>
    new ExactModelBrowserHost(pins, TRUST).registerPackage(manifest, wasm, sig);

  await assert.rejects(() => register([{ ...pin, digest: "00" }]), reason("pin_mismatch", "model_unavailable"));
  await assert.rejects(() => register([pin, { ...pin, digest: "11" }]), reason("pin_ambiguous"));
  await assert.rejects(() => register([{ ...pin, model_id: "fixture.other" }]), reason("pin_mismatch"));
  await assert.rejects(
    () => register([{ ...pin, rights: { license_id: "MIT", commercial_use: "allowed" } }]),
    reason("rights_mismatch"),
  );
  await assert.rejects(
    () => register([{ ...pin, rights: { license_id: "Apache-2.0", commercial_use: "prohibited" } }]),
    reason("rights_mismatch"),
  );
  await assert.rejects(() => register([pin], pkg.manifest, new Uint8Array([0, 1])), reason("digest_mismatch"));
  assert.throws(
    () => new ExactModelBrowserHost([{ ...pin, target: "ollama.local" }], TRUST),
    reason("candidate_unsupported"),
  );

  const cases = [
    [(m) => { m.package_digest = "legacy"; }, "manifest_invalid"],
    [(m) => { m.rights.extra = "x"; }, "manifest_invalid"],
    [(m) => { m.rights.commercial_use = "maybe"; }, "manifest_invalid"],
    [(m) => { m.max_fuel = -1; }, "manifest_invalid"],
    [(m) => { m.supported_profiles = [1]; }, "manifest_invalid"],
    [(m) => { m.offline_allowed = "yes"; }, "manifest_invalid"],
    [(m) => { m.rights.attribution = " "; }, "rights_incomplete"],
    [(m) => { m.executable_format = ""; }, "manifest_invalid"],
    [(m) => { m.schema_version = "1.0.0"; }, "manifest_invalid"],
    [(m) => { m.max_execution_ms = 0; }, "manifest_invalid"],
    [(m) => { m.supported_profiles = ["gpu"]; }, "target_unsupported"],
  ];
  for (const [edit, expected] of cases) {
    const { bytes, sig } = resigned(pkg.manifest, edit);
    const editedPin = await pinFor("fixture.echo", bytes);
    await assert.rejects(() => register([editedPin], bytes, pkg.wasm, sig), reason(expected), expected);
  }
});

test("missing WebCrypto Ed25519 fails closed with crypto_unavailable", async () => {
  const pkg = fixture("fixture-echo-1.0.0");
  const pin = await pinFor("fixture.echo", pkg.manifest);
  const host = new ExactModelBrowserHost([pin], TRUST);
  const original = crypto.subtle.importKey;
  crypto.subtle.importKey = async () => {
    throw new DOMException("Ed25519 unsupported", "NotSupportedError");
  };
  try {
    await assert.rejects(
      () => host.registerPackage(pkg.manifest, pkg.wasm, pkg.sig),
      reason("crypto_unavailable", "model_unavailable"),
    );
  } finally {
    crypto.subtle.importKey = original;
  }
});

test("execute enforces cancellation, timeout, resource ceilings, schema, policy, and cache tampering", async () => {
  const { host, digest } = await registeredHost("fixture-echo-1.0.0", "fixture.echo");
  const stage = () => host.io.stageModelInput(new Uint8Array([1, 2, 3]), 64);
  const run = (extra) => host.execute(executeArgs("fixture.echo", digest, stage(), "schema:fixture-in", extra));

  const aborted = new AbortController();
  aborted.abort();
  await assert.rejects(() => run({ signal: aborted.signal }), (e) => e.code === "cancelled");
  const midway = new AbortController();
  const pending = run({ signal: midway.signal });
  midway.abort();
  await assert.rejects(() => pending, (e) => e.code === "cancelled");
  await assert.rejects(() => run({ timeout_ms: -1 }), (e) => e.code === "timeout");
  await assert.rejects(() => run({ policy_ref: "" }), (e) => e.code === "policy_denied");
  await assert.rejects(() => run({ data_classification: "secret" }), (e) => e.code === "policy_denied");
  await assert.rejects(() => run({ input_schema_ref: "schema:other" }), (e) => e.code === "model_incompatible");
  await assert.rejects(
    () =>
      host.execute(
        executeArgs("fixture.echo", digest, host.io.stageModelInput(new Uint8Array(5000), 8000), "schema:fixture-in"),
      ),
    (e) => e.code === "resource_exhausted",
  );

  // Memory ceiling below what the staged windows need.
  const pkg = fixture("fixture-echo-1.0.0");
  const tiny = resigned(pkg.manifest, (m) => {
    m.max_memory_bytes = 128;
  });
  const tinyHost = new ExactModelBrowserHost([await pinFor("fixture.echo", tiny.bytes)], TRUST);
  const tinyDigest = await tinyHost.registerPackage(tiny.bytes, pkg.wasm, tiny.sig);
  await assert.rejects(
    () =>
      tinyHost.execute(
        executeArgs("fixture.echo", tinyDigest, tinyHost.io.stageModelInput(new Uint8Array([1]), 8), "schema:fixture-in"),
      ),
    (e) => e.code === "resource_exhausted",
  );

  // Tampered cache bytes fail the per-execute digest re-check.
  host.packages.get(digest).wasm[0] ^= 0xff;
  await assert.rejects(() => run({}), reason("digest_mismatch"));
});

test("artifact refs are multi-read, bounded, opaque, and separate from model refs", () => {
  const io = new ModelIoStore();
  assert.throws(() => io.stageArtifact(new Uint8Array(0), 8), (e) => e instanceof ExactModelError && e.code === "input_limit_exceeded");
  assert.throws(() => io.stageArtifact(new Uint8Array(6), 4), (e) => e.code === "input_limit_exceeded");
  const bytes = Uint8Array.from([1, 2, 3]);
  const ref = io.stageArtifact(bytes, 8);
  assert.equal(ref, "artifact-1");
  assert.ok(!ref.includes("/") && !ref.includes(":"));
  // Bytes are copied in and out: caller mutation never reaches the store.
  bytes[0] = 9;
  const first = io.readArtifact(ref, 8);
  first[1] = 9;
  assert.deepEqual([...io.readArtifact(ref, 8)], [1, 2, 3]);
  assert.throws(() => io.readArtifact(ref, 2), (e) => e.code === "input_limit_exceeded");
  assert.throws(() => io.readArtifact("artifact-9", 8), (e) => e.code === "unavailable");
  const inputRef = io.stageModelInput(Uint8Array.from([1]), 8);
  assert.throws(() => io.readArtifact(inputRef, 8), (e) => e.code === "unavailable");
  io.takeInput(inputRef);
  assert.throws(() => io.takeInput(inputRef), (e) => e.code === "invalid_input");
  assert.deepEqual([...io.readArtifact(ref, 8)], [1, 2, 3]);
  io.dropRef(ref);
  assert.throws(() => io.readArtifact(ref, 8), (e) => e.code === "unavailable");
});

test("shutdown invalidates every staged ref", () => {
  const io = new ModelIoStore();
  const artifactRef = io.stageArtifact(Uint8Array.from([1]), 8);
  const inputRef = io.stageModelInput(Uint8Array.from([1]), 8);
  const outputRef = io.putOutput(Uint8Array.from([1]));
  io.shutdown();
  assert.throws(() => io.readArtifact(artifactRef, 8), (e) => e.code === "unavailable");
  assert.throws(() => io.takeInput(inputRef), (e) => e.code === "invalid_input");
  assert.throws(() => io.readModelOutput(outputRef, 8), (e) => e.code === "unavailable");
});

test("guest ABI v2 (#1588): model_alloc buffers match the v1 echo; bad allocators fail closed", async () => {
  const pkg = fixture("fixture-echo-v2-1.0.0");
  const pin = await pinFor("fixture.echo-v2", pkg.manifest);
  const host = new ExactModelBrowserHost([pin], TRUST);
  const digest = await host.registerPackage(pkg.manifest, pkg.wasm, pkg.sig);
  for (const bytes of [new Uint8Array([1, 2, 3]), new Uint8Array(3000).fill(7)]) {
    const input_ref = host.io.stageModelInput(bytes, 4096);
    const result = await host.execute(executeArgs("fixture.echo-v2", digest, input_ref, "schema:fixture-in"));
    assert.deepEqual([...host.io.readModelOutput(result.output_ref, 4096)], [...bytes]);
  }

  const { default: wabtInit } = await import("wabt");
  const wabt = await wabtInit();
  const guest = (alloc) =>
    new Uint8Array(
      wabt
        .parseWat(
          "g.wat",
          `(module (memory (export "memory") 1)
             (func (export "model_alloc") (param $len i32) (result i32) ${alloc})
             (func (export "model_execute") (param i32 i32 i32 i32) (result i32) i32.const 0))`,
        )
        .toBinary({}).buffer,
    );
  const v1Echo = fixture("fixture-echo-1.0.0").wasm;
  const cases = [
    [v1Echo, "model_incompatible"],
    [guest("unreachable"), "execution_failed"],
    [guest("i32.const 0"), "execution_failed"],
    [guest("i32.const -8"), "execution_failed"],
    [guest("i32.const 2147483000"), "execution_failed"],
    [guest("i32.const 1024"), "execution_failed"],
    [guest("(drop (memory.grow (i32.const 16))) i32.const 1024"), "resource_exhausted"],
  ];
  for (const [wasm, code] of cases) {
    const { bytes, sig } = resigned(pkg.manifest, (m) => {
      m.wasm_digest = createHash("sha256").update(wasm).digest("hex");
      m.max_memory_bytes = 131072;
    });
    const casePin = await pinFor("fixture.echo-v2", bytes);
    const caseHost = new ExactModelBrowserHost([casePin], TRUST);
    const caseDigest = await caseHost.registerPackage(bytes, wasm, sig);
    const input_ref = caseHost.io.stageModelInput(new Uint8Array([1, 2, 3]), 64);
    await assert.rejects(
      () => caseHost.execute(executeArgs("fixture.echo-v2", caseDigest, input_ref, "schema:fixture-in")),
      (error) => error.code === code,
      code,
    );
  }
  const { bytes, sig } = resigned(pkg.manifest, (m) => {
    m.abi_version = 3;
  });
  const future = new ExactModelBrowserHost([await pinFor("fixture.echo-v2", bytes)], TRUST);
  await assert.rejects(() => future.registerPackage(bytes, pkg.wasm, sig), (error) => error.reason === "manifest_invalid");
});
